test_tag_parser_output = {
    "description": "An extended version of the documentary from the series finale of Silicon Valley. #HBO #SiliconValleyHBO Subscribe to HBO on YouTube: https://goo.gl/wtFYd7 Fr...",
    "form": "video",
    "image": "https://i.ytimg.com/vi/ab1H602yc_Y/maxresdefault.jpg",
    "medium": "video_link",
    "title": "Silicon Valley | Ten Years Later: The Extended Pied Piper Documentary | HBO",
    "url": "https://www.youtube.com/watch?v=ab1H602yc_Y",
}

test_get_without_og_twitter_output = {
    "description": "This site is supported by donations to The OEIS Foundation.\n",
    "form": "text",
    "image": "https://i.ibb.co/",
    "medium": "link",
    "title": "List of LaTeX mathematical symbols - OeisWiki",
    "url": "oeis.org",
}

test_enrich_imdb_movie_output = {
    "movie results": {
        "id": 278,
        "video": False,
        "vote_count": 16422,
        "vote_average": 8.7,
        "title": "The Shawshank Redemption",
        "release_date": "1994-09-23",
        "original_language": "en",
        "original_title": "The Shawshank Redemption",
        "genre_ids": [80, 18],
        "backdrop_path": "/avedvodAZUcwqevBfm8p4G2NziQ.jpg",
        "adult": False,
        "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        "poster_path": "/5KCVkau1HEl7ZzfPsKAPM0sMiKc.jpg",
        "popularity": 44.092,
    },
    "trailer": {
        "id": "533ec653c3a3685448000249",
        "iso_639_1": "en",
        "iso_3166_1": "US",
        "key": "K_tLp7T6U1c",
        "name": "The Shawshank Redemption - Trailer",
        "site": "YouTube",
        "size": 480,
        "type": "Trailer",
    },
    "wiki data": {
        "Directed by": ["Frank Darabont"],
        "Produced by": ["Niki Marvin"],
        "Screenplay by": ["Frank Darabont"],
        "Based on": ["Rita Hayworth and Shawshank Redemption", "by", "Stephen King"],
        "Starring": [
            "Tim Robbins",
            "Morgan Freeman",
            "Bob Gunton",
            "William Sadler",
            "Clancy Brown",
            "Gil Bellows",
            "James Whitmore",
        ],
        "Music by": ["Thomas Newman"],
        "Cinematography": ["Roger Deakins"],
        "Edited by": ["Richard Francis-Bruce"],
        "Production": ["company", "Castle Rock Entertainment"],
        "Distributed by": ["Columbia Pictures"],
        "Release date": [
            "September 10, 1994",
            "1994-09-10",
            "TIFF",
            "September 23, 1994",
            "1994-09-23",
            "(United States)",
        ],
        "Running time": ["142 minutes"],
        "Country": ["United States"],
        "Language": ["English"],
        "Budget": ["$25 million"],
        "Box office": ["$58.3 million"],
    },
}

test_enrich_imdb_tv_output = {
    "tv_results": {
        "original_name": "Game of Thrones",
        "id": 1399,
        "name": "Game of Thrones",
        "vote_count": 8647,
        "vote_average": 8.3,
        "first_air_date": "2011-04-17",
        "poster_path": "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
        "genre_ids": [18, 10765],
        "original_language": "en",
        "backdrop_path": "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
        "overview": "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
        "origin_country": ["US"],
        "popularity": 74.831,
    },
    "trailer": {
        "id": "5c9295200e0a267cd8168bd8",
        "iso_639_1": "en",
        "iso_3166_1": "US",
        "key": "BpJYNVhGf1s",
        "name": "Game of Thrones | Season 1 | Official Trailer",
        "site": "YouTube",
        "size": 1080,
        "type": "Trailer",
    },
    "wiki data": {
        "Genre": ["Fantasy", "Serial drama", "Tragedy"],
        "Created by": ["David Benioff", "D. B. Weiss"],
        "Based on": ["A Song of Ice and Fire", "by", "George R. R. Martin"],
        "Starring": ["see", "List of", "Game of Thrones", "characters"],
        "Theme music composer": ["Ramin Djawadi"],
        "Opening theme": ['"', 'Main Title"'],
        "Composer(s)": ["Ramin Djawadi"],
        "Country of origin": ["United States"],
        "Original": ["language(s)", "English"],
        "No": ["of episodes", "73", "list of episodes"],
        "Executive": [
            "producer(s)",
            "List",
            "David Benioff",
            "D. B. Weiss",
            "Carolyn Strauss",
            "Frank Doelger",
            "Bernadette Caulfield",
            "Bryan Cogman",
            "Miguel Sapochnik",
            "David Nutter",
        ],
        "Producer(s)": [
            "List",
            "Mark Huffam",
            "Joanna Burn",
            "Frank Doelger",
            "Chris Newman",
            "Greg Spence",
            "Lisa McAtackney",
            "Bryan Cogman",
            "Duncan Muggoch",
        ],
        "Production location(s)": [
            "Northern Ireland",
            "Croatia",
            "Iceland",
            "Spain",
            "Malta",
            "Morocco",
            "Canada",
        ],
        "Running time": ["50–82 minutes"],
        "Production": [
            "company(s)",
            "Television 360",
            "Grok! Television",
            "Generator Entertainment",
            "Startling Television",
            "Bighead Littlehead",
        ],
        "Distributor": ["Warner Bros. Television Distribution"],
        "Original network": ["HBO"],
        "Picture format": ["HDTV", "1080i"],
        "Audio format": ["Dolby Digital 5.1"],
        "Original release": [
            "April 17, 2011",
            "2011-04-17",
            "–",
            "May 19, 2019",
            "2019-05-19",
        ],
        "Related shows": ["Thronecast", "After the Thrones"],
    },
}

test_enrich_imdb_person_output = {
    "person data": {
        "birthday": "1970-07-30",
        "known_for_department": "Directing",
        "deathday": None,
        "id": 525,
        "name": "Christopher Nolan",
        "also_known_as": [
            "Кристофер Нолан",
            "Крістофер Нолан",
            "克里斯托弗·诺兰",
            "คริสโตเฟอร์ โนแลน",
            "クリストファー・ノーラン",
            "كريستوفر نولان",
            "크리스토퍼 놀란",
            "Κρίστοφερ Νόλαν",
            "Christopher Edward Nolan",
        ],
        "gender": 2,
        "biography": "Christopher Edward Nolan, CBE (born 30 July 1970) is a British-American film director, screenwriter, and producer. He was born in Westminster, London, England and holds both British and American citizenship due to his American mother. He is known for writing and directing critically acclaimed films such as Memento (2000), The Prestige (2006), The Dark Knight Trilogy (2005-12), Inception (2010), Interstellar (2014) and Dunkirk (2017). Nolan is the founder of the production company Syncopy Films. He often collaborates with his wife, producer Emma Thomas, and his brother, screenwriter Jonathan Nolan.",
        "popularity": 10.164,
        "place_of_birth": "Westminster, London, England, UK",
        "profile_path": "/iG0Gs0i5yd6SG4tSFjlXi5ZnSX6.jpg",
        "adult": False,
        "imdb_id": "nm0634240",
        "homepage": None,
    },
    "wiki data": {
        "Christopher Nolan": ["CBE"],
        "Nolan at the": ["2018 Cannes Film Festival"],
        "Born": [
            "Christopher Edward Nolan",
            "1970-07-30",
            "30 July 1970",
            "(age 49)",
            "Westminster,",
            "London, England",
        ],
        "Citizenship": ["United Kingdom", "United States"],
        "Alma mater": ["University College London"],
        "Occupation": ["Filmmaker"],
        "Years active": ["1989–present"],
        "Works": ["Full list"],
        "Spouse(s)": ["Emma Thomas", "m", "1997"],
        "Children": ["4"],
        "Relatives": [
            "Jonathan Nolan (brother)",
            "John Nolan (uncle)",
            "Lisa Joy (sister-in-law)",
        ],
        "Awards": ["Full list"],
    },
}

test_enrich_goodreads_output = {
    "original_publication_year": "1999",
    "original_publication_month": "9",
    "original_publication_day": "30",
    "average_rating": "3.95",
    "author_name": "Lemony Snicket",
    "wiki data": {
        "Author": ["Lemony Snicket pen name of", "Daniel Handler"],
        "Illustrator": ["Brett Helquist"],
        "Cover artist": ["Brett Helquist"],
        "Country": ["United States"],
        "Language": ["English"],
        "Series": ["A Series of Unfortunate Events"],
        "Genre": ["Gothic fiction", "Absurdist fiction", "Mystery"],
        "Publisher": ["HarperCollins"],
        "Publication date": ["September 30, 1999"],
        "Media type": ["Print (hardback &amp; paperback)"],
        "Pages": ["162"],
        "ISBN": [
            'mw-parser-output cite.citation{font-style:inherit}.mw-parser-output .citation q{quotes:"\\"""\\"""\'""\'"}.mw-parser-output .id-lock-free a,.mw-parser-output .citation .cs1-lock-free a{background-image:url("//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Lock-green.svg/9px-Lock-green.svg.png");background-image:linear-gradient(transparent,transparent),url("//upload.wikimedia.org/wikipedia/commons/6/65/Lock-green.svg");background-repeat:no-repeat;background-size:9px;background-position:right .1em center}.mw-parser-output .id-lock-limited a,.mw-parser-output .id-lock-registration a,.mw-parser-output .citation .cs1-lock-limited a,.mw-parser-output .citation .cs1-lock-registration a{background-image:url("//upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Lock-gray-alt-2.svg/9px-Lock-gray-alt-2.svg.png");background-image:linear-gradient(transparent,transparent),url("//upload.wikimedia.org/wikipedia/commons/d/d6/Lock-gray-alt-2.svg");background-repeat:no-repeat;background-size:9px;background-position:right .1em center}.mw-parser-output .id-lock-subscription a,.mw-parser-output .citation .cs1-lock-subscription a{background-image:url("//upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Lock-red-alt-2.svg/9px-Lock-red-alt-2.svg.png");background-image:linear-gradient(transparent,transparent),url("//upload.wikimedia.org/wikipedia/commons/a/aa/Lock-red-alt-2.svg");background-repeat:no-repeat;background-size:9px;background-position:right .1em center}.mw-parser-output .cs1-subscription,.mw-parser-output .cs1-registration{color:#555}.mw-parser-output .cs1-subscription span,.mw-parser-output .cs1-registration span{border-bottom:1px dotted;cursor:help}.mw-parser-output .cs1-ws-icon a{background-image:url("//upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Wikisource-logo.svg/12px-Wikisource-logo.svg.png");background-image:linear-gradient(transparent,transparent),url("//upload.wikimedia.org/wikipedia/commons/4/4c/Wikisource-logo.svg");background-repeat:no-repeat;background-size:12px;background-position:right .1em center}.mw-parser-output code.cs1-code{color:inherit;background:inherit;border:inherit;padding:inherit}.mw-parser-output .cs1-hidden-error{display:none;font-size:100%}.mw-parser-output .cs1-visible-error{font-size:100%}.mw-parser-output .cs1-maint{display:none;color:#33aa33;margin-left:0.3em}.mw-parser-output .cs1-subscription,.mw-parser-output .cs1-registration,.mw-parser-output .cs1-format{font-size:95%}.mw-parser-output .cs1-kern-left,.mw-parser-output .cs1-kern-wl-left{padding-left:0.2em}.mw-parser-output .cs1-kern-right,.mw-parser-output .cs1-kern-wl-right{padding-right:0.2em}.mw-parser-output .citation .mw-selflink{font-weight:inherit}',
            "0-06-440766-7",
        ],
        "OCLC": ["41070636"],
        "Dewey Decimal": ["Fic 21"],
        "LC Class": ["PZ7.S6795 Bad 1999"],
        "Followed by": ["The Reptile Room"],
    },
}

test_enrich_wikiart_artwork_output = {
    "data": [
        {
            "id": "57726f82edc2cb3880bb105d",
            "title": "Chess-Players",
            "url": None,
            "artistUrl": "honore-daumier",
            "artistName": "Honore Daumier",
            "artistId": "57726d7fedc2cb3880b481f6",
            "completitionYear": 1867,
            "width": 750,
            "image": "https://uploads8.wikiart.org/images/honore-daumier/chess-players.jpg!Large.jpg",
            "height": 585,
        },
        {
            "id": "577272a0edc2cb3880c5ebd3",
            "title": "Egyptian Chess Players",
            "url": None,
            "artistUrl": "sir-lawrence-alma-tadema",
            "artistName": "Sir Lawrence Alma-Tadema",
            "artistId": "57726d84edc2cb3880b48a2b",
            "completitionYear": 1865,
            "width": 750,
            "image": "https://uploads1.wikiart.org/images/alma-tadema-lawrence/egyptian-chess-players-1865.jpg!Large.jpg",
            "height": 511,
        },
        {
            "id": "57727661edc2cb3880d14ee1",
            "title": "Portrait of Chess Players",
            "url": None,
            "artistUrl": "marcel-duchamp",
            "artistName": "Marcel Duchamp",
            "artistId": "57726d87edc2cb3880b49292",
            "completitionYear": 1911,
            "width": 573,
            "image": "https://uploads7.wikiart.org/images/marcel-duchamp/portrait-of-chess-players-1911.jpg!Large.jpg",
            "height": 600,
        },
        {
            "id": "57727663edc2cb3880d150c9",
            "title": "The Chess Players",
            "url": None,
            "artistUrl": "marcel-duchamp",
            "artistName": "Marcel Duchamp",
            "artistId": "57726d87edc2cb3880b49292",
            "completitionYear": 1911,
            "width": 706,
            "image": "https://uploads8.wikiart.org/images/marcel-duchamp/the-chess-players-1911.jpg!Large.jpg",
            "height": 600,
        },
        {
            "id": "57727903edc2cb3880d9e170",
            "title": "Portrait of chess player A. D.  Petrova",
            "url": None,
            "artistUrl": "grigoriy-myasoyedov",
            "artistName": "Grigoriy Myasoyedov",
            "artistId": "57726d8bedc2cb3880b49aea",
            "completitionYear": None,
            "width": 384,
            "image": "https://uploads8.wikiart.org/images/grigoriy-myasoyedov/portrait-of-chess-player-a-d-petrova.jpg",
            "height": 550,
        },
        {
            "id": "57727e43edc2cb3880ea56d9",
            "title": "Sketch for The Chess Players",
            "url": None,
            "artistUrl": "thomas-eakins",
            "artistName": "Thomas Eakins",
            "artistId": "57726d9aedc2cb3880b4b6e8",
            "completitionYear": None,
            "width": 493,
            "image": "https://uploads4.wikiart.org/images/thomas-eakins/sketch-for-the-chess-players.jpg!Large.jpg",
            "height": 600,
        },
        {
            "id": "57727e45edc2cb3880ea599c",
            "title": "The Chess Player",
            "url": None,
            "artistUrl": "thomas-eakins",
            "artistName": "Thomas Eakins",
            "artistId": "57726d9aedc2cb3880b4b6e8",
            "completitionYear": 1876,
            "width": 750,
            "image": "https://uploads6.wikiart.org/images/thomas-eakins/the-chess-player-1876.jpg!Large.jpg",
            "height": 544,
        },
        {
            "id": "57728019edc2cb3880f004dd",
            "title": "The Chess Player",
            "url": None,
            "artistUrl": "corneliu-baba",
            "artistName": "Corneliu Baba",
            "artistId": "57726da3edc2cb3880b4c802",
            "completitionYear": 1948,
            "width": 348,
            "image": "https://uploads5.wikiart.org/images/corneliu-baba/the-chess-player-1948.jpg",
            "height": 400,
        },
        {
            "id": "57728380edc2cb3880fabf99",
            "title": "Chess Players",
            "url": None,
            "artistUrl": "ernest-meissonier",
            "artistName": "Ernest Meissonier",
            "artistId": "57726dbbedc2cb3880b4ed63",
            "completitionYear": 1853,
            "width": 750,
            "image": "https://uploads7.wikiart.org/images/ernest-meissonier/chess-players-1853.jpg!Large.jpg",
            "height": 588,
        },
        {
            "id": "577283a6edc2cb3880fb4eef",
            "title": "The Chess Players",
            "url": None,
            "artistUrl": "john-lavery",
            "artistName": "John Lavery",
            "artistId": "57726dbcedc2cb3880b4ef5b",
            "completitionYear": 1929,
            "width": 750,
            "image": "https://uploads5.wikiart.org/images/john-lavery/the-chess-players-1929.jpg!Large.jpg",
            "height": 480,
        },
        {
            "id": "5772842bedc2cb3880fd1a37",
            "title": "Chess Players III",
            "url": None,
            "artistUrl": "willi-baumeister",
            "artistName": "Willi Baumeister",
            "artistId": "57726dc1edc2cb3880b4f87c",
            "completitionYear": 1924,
            "width": 355,
            "image": "https://uploads0.wikiart.org/images/willi-baumeister/chess-players-iii-1924.jpg",
            "height": 451,
        },
        {
            "id": "5772893dedc2cb38800d231b",
            "title": "The Chess Players",
            "url": None,
            "artistUrl": "william-orpen",
            "artistName": "William Orpen",
            "artistId": "57726dfbedc2cb3880b552a2",
            "completitionYear": 1902,
            "width": 464,
            "image": "https://uploads7.wikiart.org/images/william-orpen/the-chess-players-1902.jpg!Large.jpg",
            "height": 600,
        },
        {
            "id": "5c7f810cedc2c95a04e53552",
            "title": "Chess Player",
            "url": None,
            "artistUrl": "max-oppenheimer",
            "artistName": "Max Oppenheimer",
            "artistId": "5c7bc0f9edc2c911c8eaf361",
            "completitionYear": 1916,
            "width": 576,
            "image": "https://uploads1.wikiart.org/00226/images/max-oppenheimer/chess-player-1916.jpg",
            "height": 450,
        },
    ],
    "paginationToken": "mYYKCPvUlMCe%2bm%2bFr5oqhRUwpA2NgYOK%2fqurC%2bhv3IPFO0G5x7nxRaZ3JcZqONEG2ICeCVS8n78enlsBEi8VqA%3d%3d",
    "hasMore": False,
}
